-- Migración 140: tipo de notificación CAMPANA_COMPLETADA.
--
-- Cuando el cron de envíos termina de procesar todos los emails de una
-- campaña/envío masivo (v1.0.179), notifica al PAS con este tipo.
-- Mensaje: "Campaña X — N enviados, M fallaron, K excluidos".

BEGIN;

-- Reconstruir el CHECK constraint de notificaciones.tipo
ALTER TABLE public.notificaciones
  DROP CONSTRAINT IF EXISTS notificaciones_tipo_check;

ALTER TABLE public.notificaciones
  ADD CONSTRAINT notificaciones_tipo_check
  CHECK (tipo IN (
    'POLIZA_VENCIDA', 'POLIZA_POR_VENCER', 'TAREA_VENCIDA', 'TAREA_HOY',
    'SINIESTRO_30_DIAS', 'SINIESTRO_60_DIAS',
    'COTIZACION_SIN_RESPUESTA', 'COTIZACION_SIN_SEGUIMIENTO',
    'OPORTUNIDAD_ESTANCADA',
    'COTIZACION_VENCIENDO_PRONTO', 'COTIZACION_VENCIDA',
    'IMPORTACION_INICIADA', 'IMPORTACION_ANALIZADA', 'IMPORTACION_LISTA_REVISION',
    'IMPORTACION_COMPLETADA', 'IMPORTACION_FALLIDA', 'IMPORTACION_PAUSADA',
    'IMPORTACION_DESHECHA',
    'PDF_LISTO_PARA_REVISAR', 'PDF_FALLIDO',
    'POLIZA_REHABILITADA',
    'BACKUP_FALLIDO', 'BACKUP_SYNC_FALLIDO',
    'RESTAURACION_INICIADA', 'RESTAURACION_COMPLETADA', 'RESTAURACION_FALLIDA',
    'EMAIL_AUTOMATICO_FALLIDO', 'COLA_EMAILS_ATRASADA',
    'SINIESTRO_DENUNCIA_PUBLICA',
    'SOLICITUD_BLANQUEO_PASSWORD', 'BLANQUEO_ABUSO_DETECTADO',
    'LICENCIA_POR_VENCER', 'LICENCIA_VENCIDA',
    'LICENCIA_EN_GRACIA', 'LICENCIA_BLOQUEADA',
    'LICENCIA_CARGADA', 'LICENCIA_PROMOVIDA',
    'ACTUALIZACION_DISPONIBLE', 'ACTUALIZACION_PROGRAMADA',
    'ACTUALIZACION_COMPLETADA', 'ACTUALIZACION_FALLIDA',
    'LEAD_WEB_NUEVO',
    'RENOVACION_COMPARACION_LISTA', 'RENOVACION_COMPARACION_FALLIDA',
    'CAMPANA_COMPLETADA'
  ));

-- Reconstruir el CHECK constraint de configuracion_notificaciones.tipo (incluye BIENVENIDA_SIN_EMAIL)
ALTER TABLE public.configuracion_notificaciones
  DROP CONSTRAINT IF EXISTS configuracion_notificaciones_tipo_check;

ALTER TABLE public.configuracion_notificaciones
  ADD CONSTRAINT configuracion_notificaciones_tipo_check
  CHECK (tipo IN (
    'POLIZA_VENCIDA', 'POLIZA_POR_VENCER', 'TAREA_VENCIDA', 'TAREA_HOY',
    'SINIESTRO_30_DIAS', 'SINIESTRO_60_DIAS',
    'COTIZACION_SIN_RESPUESTA', 'COTIZACION_SIN_SEGUIMIENTO',
    'OPORTUNIDAD_ESTANCADA',
    'COTIZACION_VENCIENDO_PRONTO', 'COTIZACION_VENCIDA',
    'IMPORTACION_INICIADA', 'IMPORTACION_ANALIZADA', 'IMPORTACION_LISTA_REVISION',
    'IMPORTACION_COMPLETADA', 'IMPORTACION_FALLIDA', 'IMPORTACION_PAUSADA',
    'IMPORTACION_DESHECHA',
    'PDF_LISTO_PARA_REVISAR', 'PDF_FALLIDO',
    'POLIZA_REHABILITADA',
    'BACKUP_FALLIDO', 'BACKUP_SYNC_FALLIDO',
    'RESTAURACION_INICIADA', 'RESTAURACION_COMPLETADA', 'RESTAURACION_FALLIDA',
    'EMAIL_AUTOMATICO_FALLIDO', 'COLA_EMAILS_ATRASADA',
    'SINIESTRO_DENUNCIA_PUBLICA',
    'SOLICITUD_BLANQUEO_PASSWORD', 'BLANQUEO_ABUSO_DETECTADO',
    'LICENCIA_POR_VENCER', 'LICENCIA_VENCIDA',
    'LICENCIA_EN_GRACIA', 'LICENCIA_BLOQUEADA',
    'LICENCIA_CARGADA', 'LICENCIA_PROMOVIDA',
    'ACTUALIZACION_DISPONIBLE', 'ACTUALIZACION_PROGRAMADA',
    'ACTUALIZACION_COMPLETADA', 'ACTUALIZACION_FALLIDA',
    'LEAD_WEB_NUEVO',
    'RENOVACION_COMPARACION_LISTA', 'RENOVACION_COMPARACION_FALLIDA',
    'BIENVENIDA_SIN_EMAIL',
    'CAMPANA_COMPLETADA'
  ));

COMMIT;
